const ALERT = "ALERT";
const REFETCH_ALERT = "REFETCH_ALERT";

const NEW_ATTACHMENT = "NEW_ATTACHMENT";
const NEW_MESSAGE_ALERT = "NEW_MESSAGE_ALERT";

const NEW_REQUEST = "NEW_REQUEST";

const NEW_MESSAGE = "NEW_MESSAGE";

const START_TYPING_MESSAGE = "START_TYPING_MESSAGE";
const STOP_TYPING_MESSAGE = "STOP_TYPING_MESSAGE";

export {
  ALERT,
  REFETCH_ALERT,
  NEW_ATTACHMENT,
  NEW_MESSAGE_ALERT,
  NEW_REQUEST,
  NEW_MESSAGE,
  START_TYPING_MESSAGE,
  STOP_TYPING_MESSAGE,
};
